# Generated by Django 3.0.8 on 2021-03-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(help_text='URL for your GitHub.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(help_text='URL for your LinkedIn page.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.URLField(help_text='URL for your Twitter feed.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.URLField(help_text='URL for your personal website.', null=True),
        ),
    ]
