version: "3.7"

networks:
  webservice_network:
    driver: bridge

services:
  django:
    image: devroastproject
    networks: [webservice_network]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app/code
    env_file:
      - ./.env
    depends_on:
      - postgres
    restart: always
    #command: sh ./startup_scripts.sh

  react:
    networks: [webservice_network]
    build:
      context: .
      dockerfile: Dockerfile.react
    stdin_open: true
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - postgres
      - django
    volumes:
      - type: bind
        source: ./frontend/react-frontend
        target: /app
      - "/app/node_modules"

  postgres:
    image: postgres:12.2-alpine
    networks: [webservice_network]
    volumes:
      - devroast:/var/lib/postgresql/data/
    ports:
      - 543:5432
    env_file:
      - ./.env

  redis:
    image: redis:5.0.3-alpine
    networks: [webservice_network]
    dns:
      - 8.8.8.8

volumes:
  devroast:
