# Generated by Django 3.0.8 on 2020-10-29 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(help_text='Enter your comment here.')),
                ('neg_votes', models.IntegerField(help_text='Click to vote in favor of this comment.')),
                ('pos_votes', models.IntegerField(help_text='Click to vote against this comment.')),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of your project.', max_length=250)),
                ('repo_url', models.CharField(help_text="URL to your project's source code.", max_length=250)),
                ('hosted_url', models.CharField(help_text="Your website's URL.", max_length=250)),
                ('description', models.TextField(help_text='A brief description of your website.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(help_text='Name of your tag', max_length=200)),
                ('description', models.CharField(help_text='A brief description of the tag.', max_length=500)),
                ('comment', models.ManyToManyField(to='project.Comment')),
                ('project', models.ManyToManyField(to='project.Project')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.Project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
